default_language_version:
    python: python3.8
exclude: gtcameramodel/archive
repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    -   id: codespell
        name: 'Lyft: english grammar'
        args: [--skip=*.yaml]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        name: 'Python: auto-format source code'
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        name: 'Python: reorder imports'
        args: [--py38-plus]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        name: 'Python: linting'
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        name: 'Python: upgrade'
        args:
        -   --py38-plus
        -   --keep-runtime-typing
-   repo: git@github.com:lyft/lcs-precommit-hook.git
    rev: v0.0.8
    hooks:
    -   id: lcs
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-retry==0.9.9
        -   types-requests==2.29.0.0
